### ISSUE TITLE
Update versioncode

### ISSUE THREAD

**Issue by ghost** [mannyamorim/MetricTime#9]
`app/build.gradle` says this is version 1.0 with versioncode 2. See https://developer.android.com/studio/publish/versioning.html for details.

**Comment by mannyamorim** [comment]
Thanks for telling me this. Forgot to change the version code. I will put up a new version with the correct code.

**Comment by mannyamorim** [comment]
Fixed in commit ce342a5044184c486d872f279c106dce65efd763. New version tagged v0.0.3 with versioncode 3.
